FIND_PATH(WSLAY_INCLUDE_DIR NAMES wslay/wslay.h)
FIND_LIBRARY(WSLAY_LIBRARIES NAMES wslay libwslay libnettle)


message("**** ${WSLAY_LIBRARIES} *****")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WSLAY DEFAULT_MSG WSLAY_LIBRARIES WSLAY_INCLUDE_DIR)
